language: dart
dart:
  - stable
global:
  - GH_REF: github.com/Klikini/TicTacToe3.git
  - secure: "kP+25nRVIzRqH1uIDJQnMZOat3mI9sJBrP+quf7+judpijhqMYfZ5TUH0+rc1jOxGgchE5PLEnaBs8oBWw4R8auVVVoshm5KAVt7m9kMD5f6Cz+9bBtd5Tck5E8khLCxCFD5Go9UDoiXJy6zxpNhohr1ba9oL//sHBtGja3K7RJNr8bMY52/kRJOw5mt0PLryAA8s4RbKABUPzne8TGW9zkTBbdfzbwbqT8Cvxtko9F/Pq+EytPM/spdX2NH/nSmLgGtKVlcfVIJfTxAgQfXP7OADG5IY9HpjgUnicF+TzB/1rnGj1gHJyOcx6J3BW946wc1Jtwt0reL/lTRo6Vuem/Q8OF5z5QSh1Y5Dteam1ais2Ut7NisWV5pMt1Vsqy4TNzllJgAJymVIXn1FL/g5aEDuA68z+2A1C7VL/Bk0iBaOfvebmfrDTiYvqyX75TmhcBMcn+/cZExLMEqYT7K2HIfKghq1uWN18Q76/D8gY7V5mELUor5jwQSSoe40fCtDa4hEB2tCV3OfgcgUM0bgUFStHQMUEadCju+0nBp2l1elJbyzwvl/qVyXvD2BFk1oMupNFSFqMVjd/cgaP3+wB7HaK32X1oIOodmPCy1p85pAzJ9GidAElBqI+b2YpypU4gT6f07auN5i8UJQsMBtkU4/zSk98B8l+Ud35HWOhk="
