name: TicTacToe3
description: 3-player tic tac toe
dependencies:
  browser: any
  konami_code: any
  transmit:
    git: git://github.com/Klikini/transmit.git
transformers:
- $dart2js:
    commandLineOptions: [--enable-enums]